### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by karthi81** [CiscoUcs/intersight-python#36]
(ucs_ops) [vagrant@cisco-vagrant cimc_ansible]$ python claim_device.py --help
Traceback (most recent call last):
  File "claim_device.py", line 10, in <module>
    import device_connector
ImportError: No module named device_connector
(ucs_ops) [vagrant@cisco-vagrant cimc_ansible]$

device_connector is is available and tested on python 2.7 and 3.6

Can you please take a look?

**Comment by szolucha** [comment]
If I run it from intersight-python-master path:
I have the same problem: ModuleNotFoundError: No module named 'device_connector' of

$ py claim_device.py -a intersight_api_params -d devices
Traceback (most recent call last):
  File "claim_device.py", line 10, in <module>
    import device_connector
ModuleNotFoundError: No module named 'device_connector'



if I run in from intersight-python-master\examples path
I have a different problem: No module named 'intersight.intersight_api_client'

$ py claim_device.py -a intersight_api_params -d devices
Traceback (most recent call last):
  File "claim_device.py", line 8, in <module>
    from intersight.intersight_api_client import IntersightApiClient
ModuleNotFoundError: No module named 'intersight.intersight_api_client'


-----
$ python -V
Python 3.7.0

-----

$ pip list
Package         Version
certifi         2021.5.30
cffi            1.14.5
chardet         4.0.0
cryptography    3.4.7
idna            2.10
intersight      1.0.9.5808
pem             21.2.0
pip             22.0.4
pycparser       2.20
pycryptodome    3.14.1
pycryptodomex   3.14.1
PySimpleGUI     4.45.0
python-dateutil 2.8.2
requests        2.25.1
setuptools      62.0.0
six             1.16.0
tabulate        0.8.9
urllib3         1.26.5
wheel           0.37.1

**Comment by dsoper2** [comment]
With newer python SDKs (installed with PIP), the claim_target.py script from https://github.com/CiscoDevNet/intersight-python-utils/tree/master/config_targets can be used.  Example usage is the following (needs to be run from the config_targets subdir):
 
python claim_target.py -t sjc07_devices.json
 
The older claim_device.py script does not work with newer SDKs.

**Comment by szolucha** [comment]
My current Iintersight package ver. is 1.0.9.5808. It seems to be the latest per pypi.org:
https://pypi.org/search/?q=intersight
intersight 1.0.9.5808

Dave are you referring to intersight-rest: intersight-rest 1.1.7 ?
Thx for quick turn around!

Derek
